# This is a basic workflow to help you get started with Actions

name: armTimeplateDeployment

on:
  push:
    branches:
      - main  
  workflow_dispatch:
jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resource group rg-githubactions-sdl with arm deploy
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: eastus
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions-sdl 

      - name: Deploy storage account
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions-sdl
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          template: ./arm-templates/storageaccount.json
          parameters: ./arm-templates/storageacount.parameters.json
          deploymentMode: incremental 
