# This is a basic workflow to help you get started with Actions

name: armTimeplateDeployment

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  resource_group_name: rg-githubactions-sdl
  location: eastus

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure key vault - Get Secrets
        uses: Azure/get-keyvault-secrets@v1.2
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          keyvault: ${{ secrets.AZURE_KEYVAULT }}
          secrets: 'AdminPassword'
        id: MygithubactionsKV

      - name: Deploy Azure Resource group ${{ env.resource_group_name }} with arm deploy
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: ${{ env.location }}
          template: ./arm-templates/resourcegroup.json
          deploymentName: ${{ env.resource_group_name }} 

      - name: Deploy storage account
        uses: Azure/arm-deploy@v1
        id: storageaccountdeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          template: ./arm-templates/storageaccount.json
          parameters: ./arm-templates/storageaccount.parameters.json
          deploymentMode: incremental 

      - name: Deploy virtual machine
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword=${{ steps.MygithubactionsKV.outputs.AdminPassword }}
            location=${{ env.location }}
          deploymentMode: incremental 

      - run: echo ${{ steps.MygithubactionsKV.outputs.AdminPassword }}